name: Build and Release (Simplified)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Override Java home for CI
      run: |
        # Comment out local Java path for CI
        sed -i 's/^org.gradle.java.home=/#&/' gradle.properties
        echo "Modified gradle.properties:"
        cat gradle.properties

    - name: Build with Gradle
      run: |
        echo "Building with Java 17..."
        java -version
        ./gradlew clean build --no-daemon -x dependencyCheckAnalyze --stacktrace
        echo "Build completed successfully!"
        ls -la build/libs/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mod-jar
        path: build/libs/*.jar

    - name: Create Release (Manual trigger only)
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        name: Experience Bar Fix v1.0.0
        body: |
          ## Experience Bar Fix v1.0.0
          
          Fixes experience bar disappearing issue after teleportation in Minecraft 1.20.1 with Forge 47.2.0+
          
          **Installation:**
          1. Download the jar file below
          2. Place it in your mods folder
          3. Run Minecraft with Forge
        draft: false
        prerelease: false
        files: build/libs/experiencebarfix-1.0.0.jar
